import {useState} from 'react';
import {ArrowRight,ArrowUpRight,Building2,Check,CheckCircle2,ChevronRight,ClipboardCheck,Compass,FileSearch,Globe2,MapPin,ShieldCheck,ShieldQuestion,Store,UsersRound, type LucideIcon} from 'lucide-react';
import './public.css';

const uses:{key:string;label:string;helper:string;icon:LucideIcon;checks:string[]}[]=[
 {key:'oficina',label:'Una oficina',helper:'Para trabajar y recibir clientes',icon:Building2,checks:['Accesibilidad y locomoción','Costos de ocupación','Servicios y comodidad','Uso permitido']},
 {key:'local',label:'Un local comercial',helper:'Para vender o prestar servicios',icon:Store,checks:['Flujo y actividad potencial','Accesos y visibilidad','Oferta complementaria','Permisos y habilitación']},
 {key:'vivienda',label:'Una vivienda',helper:'Para comprar o arrendar',icon:UsersRound,checks:['Tiempo a destinos habituales','Servicios cercanos','Gastos totales','Documentos y restricciones']},
 {key:'parcela',label:'Una parcela',helper:'Antes de comprometer una compra',icon:Compass,checks:['Antecedentes territoriales','Accesos y servicios','Condiciones de suelo','Documentación y restricciones']}
];
const prices=[
 {name:'Esencial',price:'$9.990',detail:'Una propiedad o ubicación',features:['Ficha de ubicación','Antecedentes con cobertura declarada','Preguntas y precauciones importantes']},
 {name:'Compara',price:'$24.990',detail:'Hasta tres alternativas',features:['Comparación según tu actividad','Costos conocidos y variables faltantes','Ventajas y limitaciones por alternativa']},
 {name:'Decisión',price:'$49.900',detail:'Alcance ampliado por caso',features:['Antecedentes más detallados','Escenarios y puntos de verificación','Revisión supervisada cuando se incluya']}
];
export default function PublicSite({onEnter}:{onEnter:()=>void}){
 const [selection,setSelection]=useState('oficina');
 const [location,setLocation]=useState('');
 const [budget,setBudget]=useState('');
 const [result,setResult]=useState(false);
 const chosen=uses.find(x=>x.key===selection)!;
 return <div className="public-site">
  <header className="public-nav"><a className="public-logo" href="#inicio"><span className="public-symbol">D<span>.</span></span><span>DEEP LIVING<small>INTELLIGENCE</small></span></a><nav aria-label="Secciones"><a href="#como">Cómo funciona</a><a href="#informes">Informes</a><a href="#metodo">Nuestro método</a></nav><button className="public-login" onClick={onEnter}>Deep Living Pro <ArrowUpRight size={16}/></button></header>
  <main id="inicio">
   <section className="public-hero"><div className="public-hero-copy"><span className="public-kicker"><span className="pulse-dot"/> INTELIGENCIA PARA DECISIONES INMOBILIARIAS</span><h1>Antes de elegir una propiedad, <em>entiende lo que estás eligiendo.</em></h1><p>Una oficina, un local, una casa o una parcela pueden verse ideales en un anuncio. Pero la decisión también depende de dónde están, para qué los necesitas y qué antecedentes aún debes comprobar.</p><div className="public-actions"><a href="#evaluar" className="public-btn primary">Explorar mi evaluación <ArrowRight size={18}/></a><a href="#como" className="public-btn outline">Conocer el método</a></div><div className="hero-trust"><span><CheckCircle2 size={16}/>Información con fuentes</span><span><CheckCircle2 size={16}/>Limitaciones explícitas</span><span><CheckCircle2 size={16}/>Sin promesas infundadas</span></div></div><div className="hero-demo"><div className="hero-demo-heading"><div><span>EJEMPLO DE ANÁLISIS</span><strong>¿Conviene esta ubicación?</strong></div><span className="live-badge">Evaluación guiada</span></div><div className="fake-map"><div className="map-grid"/><div className="map-road horizontal"/><div className="map-road vertical"/><span className="map-point one"><MapPin size={23}/></span><span className="map-point two"/><span className="map-point three"/><div className="fake-map-label">UBICACIÓN EN ANÁLISIS</div></div><div className="demo-check"><span className="check-icon"><Check size={16}/></span><div><strong>Presupuesto y requisitos</strong><small>Se comparan con la información declarada.</small></div><span className="check-ok">Evaluable</span></div><div className="demo-check"><span className="question-icon"><ShieldQuestion size={18}/></span><div><strong>Uso permitido y condiciones</strong><small>Requiere antecedentes oficiales del predio.</small></div><span className="check-wait">Pendiente</span></div><div className="demo-check"><span className="question-icon"><Globe2 size={18}/></span><div><strong>Entorno y accesibilidad</strong><small>Depende de cobertura territorial comprobada.</small></div><span className="check-wait">Por verificar</span></div><p className="demo-foot">Esta tarjeta explica nuestro enfoque. No corresponde a una evaluación real.</p></div></section>
   <section id="evaluar" className="public-explore"><div className="public-section-head"><span className="public-eyebrow">01 / EMPECEMOS POR TU OBJETIVO</span><h2>¿Qué estás pensando comprar o arrendar?</h2><p>El inmueble adecuado depende de la actividad y de tus necesidades. Por eso no utilizamos una calificación universal de «mejor propiedad».</p></div><div className="use-grid">{uses.map(u=><button key={u.key} className={'use-card '+(selection===u.key?'active':'')} onClick={()=>{setSelection(u.key);setResult(false)}}><u.icon size={23}/><strong>{u.label}</strong><small>{u.helper}</small><span className="choose-dot">{selection===u.key&&<Check size={12}/>}</span></button>)}</div><div className="evaluation-workbench"><div><span className="public-eyebrow">EVALUACIÓN INICIAL · SIN COSTO</span><h3>Ve qué aspectos conviene revisar</h3><p>Ingresa una comuna, sector o dirección de referencia. Esta demostración no consulta bases externas ni almacena datos personales.</p><form onSubmit={e=>{e.preventDefault();setResult(true)}}><label>Ubicación que estás considerando<input required value={location} onChange={e=>{setLocation(e.target.value);setResult(false)}} placeholder="Ej. Curicó, sector céntrico"/></label><label>Presupuesto máximo estimado (opcional, CLP)<input inputMode="numeric" type="number" min="0" value={budget} onChange={e=>setBudget(e.target.value)} placeholder="250000"/></label><button className="public-btn primary" type="submit">Ver puntos a comprobar <ArrowRight size={17}/></button></form></div><div className="evaluation-results"><div className="workbench-top"><strong>{result?'Tu hoja de verificación inicial':'Qué analizaríamos en tu caso'}</strong><span>{chosen.label}</span></div>{result&&<p className="result-location"><MapPin size={15}/> Referencia ingresada: {location}</p>}{chosen.checks.map((x,i)=><div className="checkline" key={x}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{x}</strong><small>{result?'Pendiente de consulta y verificación de fuentes':'Se evaluaría según cobertura y objetivos.'}</small></div><ShieldQuestion size={16}/></div>)}<p className="evaluation-disclaimer">{result?'No se ha realizado una consulta a registros oficiales. Esta lista NO es un informe sobre la ubicación ingresada.':'El informe real debe indicar fuentes, fecha, escala y datos desconocidos antes de concluir.'}</p></div></div></section>
   <section id="como" className="method-section"><div className="public-section-head"><span className="public-eyebrow">02 / CÓMO FUNCIONA</span><h2>De la duda a una decisión mejor informada.</h2><p>No somos jueces de propiedades ni calificamos la honestidad de corredores. Examinamos antecedentes, mostramos límites y sugerimos qué revisar.</p></div><div className="method-grid"><div><span>01</span><MapPin size={23}/><h3>Indicas lo que necesitas</h3><p>Uso del inmueble, alternativas, presupuesto, prioridades y ubicación.</p></div><div><span>02</span><FileSearch size={23}/><h3>Evaluamos lo verificable</h3><p>Consultamos información autorizada y distinguimos datos, estimaciones y vacíos.</p></div><div><span>03</span><ClipboardCheck size={23}/><h3>Recibes una explicación</h3><p>Comparaciones, dudas pendientes y pasos previos a comprometer dinero.</p></div></div></section>
   <section id="informes" className="pricing-section"><div className="public-section-head"><span className="public-eyebrow">03 / INFORMES</span><h2>Invierte primero en entender tu decisión.</h2><p>Precios propuestos para el piloto. La compra aún no está habilitada: los datos, cobros y condiciones deben validarse antes de aceptar pagos.</p></div><div className="public-plans">{prices.map((p,i)=><div className={'public-plan '+(i===1?'recommended':'')} key={p.name}>{i===1&&<span className="plan-tag">PROPUESTA PRINCIPAL</span>}<span className="plan-category">DEEP LIVING {p.name.toUpperCase()}</span><h3>{p.price}</h3><p>{p.detail}</p><ul>{p.features.map(f=><li key={f}><CheckCircle2 size={15}/>{f}</li>)}</ul><div className="plan-locked">Disponible tras validación del piloto</div></div>)}</div></section>
   <section id="metodo" className="ethics-section"><div className="ethics-icon"><ShieldCheck size={30}/></div><div><span className="public-eyebrow">NUESTRA REGLA DE TRABAJO</span><h2>Información clara. Sin certezas inventadas.</h2><p>Si no podemos verificar un antecedente, lo diremos. Si una condición requiere revisión jurídica o técnica, no la sustituiremos con un resultado automático. Si tenemos un interés comercial en una propiedad, debe declararse.</p></div></section>
   <section className="professional-section"><div><span className="public-eyebrow">PARA CORREDORES Y OFICINAS</span><h2>La misma evidencia. Mejor gestión de cada negocio.</h2><p>Deep Living Pro permite organizar captaciones, compradores, documentos, ofertas, pendientes, honorarios y seguimiento de operaciones, con accesos diferenciados para cada participante.</p><button className="public-btn dark" onClick={onEnter}>Conocer Deep Living Pro <ArrowRight size={17}/></button></div><div className="professional-steps"><span><CheckCircle2 size={17}/>Prechequeo antes de comercializar</span><span><CheckCircle2 size={17}/>Tareas y etapas trazables</span><span><CheckCircle2 size={17}/>Seguimiento privado para clientes</span><span><CheckCircle2 size={17}/>Honorarios y acuerdos documentados</span></div></section>
  </main><footer className="public-footer"><span>DEEP LIVING INTELLIGENCE © {new Date().getFullYear()}</span><span>Investigación y piloto en desarrollo · Chile</span><a href="#inicio">Volver al inicio <ChevronRight size={14}/></a></footer>
 </div>;
}
