import { Project } from "./ontology";

export const demoProject: Project = {
  id: "project-maule-pilot",
  name: "Proyecto piloto Maule",
  region: "Región del Maule",
  commodity: "Cu-Au",
  stage: "Investor intelligence",
  gate: "Decision readiness",
  demo: true,
  capitalAvailable: 2000000,
  currency: "USD",
  sources: [
    { id: "S1", title: "Mapa geológico regional", kind: "map", authority: "Fuente pública", verified: true },
    { id: "S2", title: "Serie operacional histórica", kind: "dataset", authority: "Operación", verified: true },
    { id: "S3", title: "Serie de precipitación", kind: "dataset", authority: "Fuente climática", verified: true },
    { id: "S4", title: "Informe técnico histórico", kind: "document", authority: "Archivo del proyecto", verified: false },
  ],
  evidence: [
    { id: "E1", sourceId: "S1", title: "Estructura regional mapeada", quality: 0.9, verified: true },
    { id: "E2", sourceId: "S2", title: "Producción mensual 2019-2026", quality: 0.94, verified: true },
    { id: "E3", sourceId: "S3", title: "Precipitación mensual 2010-2026", quality: 0.92, verified: true },
    { id: "E4", sourceId: "S4", title: "Interpretación histórica de continuidad", quality: 0.55, verified: false },
  ],
  claims: [
    {
      id: "C1",
      statement: "La operación posee una serie suficiente para comparar escenarios de producción.",
      level: "fact",
      evidenceIds: ["E2"],
      confidence: "high",
      uncertainty: [],
    },
    {
      id: "C2",
      statement: "La expansión podría aumentar exposición a restricciones hídricas estacionales.",
      level: "inference",
      evidenceIds: ["E2", "E3"],
      confidence: "moderate",
      uncertainty: ["Demanda hídrica futura", "Cambio de régimen climático"],
    },
    {
      id: "C3",
      statement: "La continuidad mineralizada hacia el NE debe tratarse como hipótesis, no como recurso.",
      level: "hypothesis",
      evidenceIds: ["E1", "E4"],
      confidence: "moderate",
      uncertainty: ["Profundidad", "Ley", "Espesor", "Continuidad"],
    },
  ],
  forecasts: [
    {
      id: "F1",
      metric: "Producción mensual",
      model: "TimesFM 2.5 adapter",
      horizon: "12 meses",
      sourceSeries: ["production_monthly", "rainfall_monthly"],
      covariates: ["precipitación", "precio cobre", "disponibilidad"],
      backtestMetric: "sMAPE",
      backtestScore: 11.8,
      baselineScore: 15.6,
      lower: 820,
      point: 960,
      upper: 1110,
      unit: "t/mes",
      validatedAt: "2026-09-18",
    },
  ],
  risks: [
    {
      id: "R1",
      title: "Restricción hídrica",
      category: "operational",
      severity: "high",
      evidenceIds: ["E3"],
      mitigation: "Modelar expansión por escenarios y verificar disponibilidad antes de CAPEX.",
    },
    {
      id: "R2",
      title: "Hipótesis geológica no confirmada",
      category: "technical",
      severity: "high",
      evidenceIds: ["E1", "E4"],
      mitigation: "Geofísica y sondajes por gates antes de escalar capital.",
    },
  ],
  decisions: [
    {
      id: "D1",
      title: "Asignación del próximo capital",
      question: "¿Dónde conviene concentrar el siguiente tramo de capital del proyecto?",
      impact: "high",
      status: "ready",
      options: [
        {
          id: "A",
          label: "Expandir operación actual",
          capital: 1400000,
          currency: "USD",
          reversible: false,
          rationale: "Aumenta capacidad usando infraestructura existente.",
        },
        {
          id: "B",
          label: "Validar target NE",
          capital: 420000,
          currency: "USD",
          reversible: true,
          rationale: "Compra información antes de comprometer mayor CAPEX.",
        },
        {
          id: "C",
          label: "Mantener liquidez",
          capital: 0,
          currency: "USD",
          reversible: true,
          rationale: "Espera evidencia adicional y conserva opcionalidad.",
        },
      ],
      evidenceIds: ["E1", "E2", "E3"],
      claimIds: ["C1", "C2", "C3"],
      forecastIds: ["F1"],
      riskIds: ["R1", "R2"],
      uncertainties: ["Agua", "Continuidad geológica", "Precio", "Costos"],
      proposedOptionId: "B",
    },
  ],
};
